version: "3"

services:
#  nginx-proxy:
#    image: jwilder/nginx-proxy
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#    networks:
#    - m2-backend

  nginx:
    image: kunrag/m2-nginx
    env_file: .env
    ports:
      - 35729:35729 #liverload
      - 443:443
      - 80:80
    links:
#      - nginx-proxy
      - fpm
    depends_on:
#      - nginx-proxy
      - fpm
    volumes: &appvolumes
      - ./src:/var/www/magento/src
      - ~/.composer:/var/www/magento/.composer
      - ~/.npm:/var/www/magento/.npm
      - m2-sockdata:/sock
    networks:
      - m2-backend
    logging:
      options:
        max-size: "2m"
        max-file: "3"

  fpm:
    image: kunrag/m2-php-7.3-fpm
    env_file: .env
    links:
      - db
    depends_on:
      - app
    volumes: *appvolumes
    networks:
      - m2-backend
    logging:
      options:
        max-size: "2m"
        max-file: "3"

  app:
    image: kunrag/m2-php-7.3-cli
    env_file: .env
    tty: true
    links:
      - db
    depends_on:
      - db
    volumes: *appvolumes
    networks:
      - m2-backend
    logging:
      options:
        max-size: "2m"
        max-file: "3"

#  cron:
#    image: kunrag/m2-php-7.3-cli
#    env_file: .env
#    command: "sudo /usr/local/bin/run-cron"
#    tty: true
#    links:
#      - db
#    depends_on:
#      - db
#    volumes: *appvolumes
#    networks:
#      - m2-backend
#    logging:
#      options:
#        max-size: "2m"
#        max-file: "3"

  db:
    image: mysql:5
   # command: --max_allowed_packet=2147483648 --max_execution_time=999999999
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - m2-dbdata:/var/lib/mysql
    networks:
      - m2-backend
    logging:
      options:
        max-size: "2m"
        max-file: "3"

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - m2-backend
    logging:
      options:
        max-size: "2m"
        max-file: "3"

  elasticsearch:
    image: elasticsearch:7.6.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=node-1
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearchdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - m2-backend

networks:
  m2-backend:
    driver: bridge

volumes:
  m2-dbdata:
  m2-sockdata:
